gpu_id: 0
use_gpu: True
seed: 212
state: INFO
reproducibility: True
data_path: 'dataset/'
checkpoint_dir: 'saved'
show_progress: True
save_dataset: False
save_dataloaders: False
# benchmark_filename: None

#dataset
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp
# seq_len: None
# LABEL_FIELD: label
# threshold: None
# NEG_PREFIX: neg_
load_col:
    inter: [user_id, item_id, timestamp]
    item: ['item_id', 'categories', 'music_type']
    user: ['user_id']
MAX_ITEM_LIST_LENGTH: 50

# Training Hyper Parameters:
# checkpoint_dir: saved/Amazon_Beauty/SASRecD_4_8_['categories']_[64]_gate_[10]_50_2048_256_0.0001_212
epochs: 200
# train_batch_size: 2048
train_batch_size: 1024
learner: adam
learning_rate: 0.0001
eval_step: 2
stopping_step: 10
clip_grad_norm: ~
weight_decay: 0.0
loss_decimal_place: 4

# Evaluation Hyper Parameters:
eval_args: {'split': {'LS': 'valid_and_test'}, 'group_by': 'user', 'order': 'TO', 'mode': 'full'}
metrics: ['Recall', 'NDCG']
topk: [5, 10, 20]
valid_metric: Recall@10
valid_metric_bigger: True
eval_batch_size: 256
metric_decimal_place: 4


#filtering
val_interval: ~
filter_inter_by_user_or_item: True
user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"


ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
POSITION_FIELD: position_id
HEAD_ENTITY_ID_FIELD: head_id
TAIL_ENTITY_ID_FIELD: tail_id
RELATION_ID_FIELD: relation_id
ENTITY_ID_FIELD: entity_id

# Other Hyper Parameters: 
neg_sampling: None
repeatable: True
n_layers: 4
n_heads: 8
hidden_size: 256
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.3
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
selected_features: ['categories']
pooling_mode: 'sum'
loss_type: 'CE'
# MODEL_TYPE: ModelType.SEQUENTIAL
attribute_hidden_size: [64]
# weight_sharing: not
fusion_type: 'gate'
lamdas: [10]
attribute_predictor: 'linear'
device: cuda
